package cum.jesus.cts.lexing;

public enum TokenType {
    ERROR,
    EOF,

    IDENTIFIER,
    TYPE,
    INTEGER_LITERAL,
    STRING_LITERAL,

    LEFT_PAREN, RIGHT_PAREN, // ()
    LEFT_BRACKET, RIGHT_BRACKET, // []
    LEFT_BRACE, RIGHT_BRACE, // {}
    LEFT_ANGLE_BRACKET, RIGHT_ANGLE_BRACKET, // <>
    LEFT_ANGLE_BRACKET_EQUALS, RIGHT_ANGLE_BRACKET_EQUALS,

    SEMICOLON, COMMA,
    DOT,

    PLUS, MINUS,
    STAR, SLASH,
    BANG, BANG_EQUALS,

    ASPERAND,
    AMPERSAND,

    EQUALS, DOUBLE_EQUALS,

    KEYWORD_NATIVE,
    KEYWORD_FUNC,
    KEYWORD_RETURN,

    KEYWORD_STRUCT,

    KEYWORD_IF,
    KEYWORD_ELSE,

    BUILTIN_CODE,
}
